// User Types
export const LOAD_SPINNER = 'LOAD_SPINNER';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// About Company Types
export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST';
export const COMPANY_FETCH_SUCCESS = 'COMPANY_FETCH_SUCCESS';
export const COMPANY_FETCH_FAILED = 'COMPANY_FETCH_FAILED';

export const PROCESS_FETCH_REQUEST = 'PROCESS_FETCH_REQUEST';
export const PROCESS_FETCH_SUCCESS = 'PROCESS_FETCH_SUCCESS';
export const PROCESS_FETCH_FAIL = 'PROCESS_FETCH_FAIL';
