// User Types
export const LOAD_SPINNER = 'LOAD_SPINNER';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// About Company Types
export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST';
export const COMPANY_FETCH_SUCCESS = 'COMPANY_FETCH_SUCCESS';
export const COMPANY_FETCH_FAILED = 'COMPANY_FETCH_FAILED';

export const PROCESS_FETCH_REQUEST = 'PROCESS_FETCH_REQUEST';
export const PROCESS_FETCH_SUCCESS = 'PROCESS_FETCH_SUCCESS';
export const PROCESS_FETCH_FAIL = 'PROCESS_FETCH_FAIL';
export const PROCESS_ADD_REQUEST = 'PROCESS_ADD_REQUEST';
export const PROCESS_ADD_SUCCESS = 'PROCESS_ADD_SUCCESS';
export const PROCESS_ADD_FAIL = 'PROCESS_ADD_FAIL';
export const PROCESS_SEARCH_REQUEST = 'PROCESS_SEARCH_REQUEST';
export const PROCESS_SEARCH_SUCCESS = 'PROCESS_SEARCH_SUCCESS';
export const PROCESS_SEARCH_FAIL = 'PROCESS_SEARCH_FAIL';
export const PROCESS_INFO_REQUEST = 'PROCESS_INFO_REQUEST';
export const PROCESS_INFO_SUCCESS = 'PROCESS_INFO_SUCCESS';
export const PROCESS_INFO_FAIL = 'PROCESS_INFO_FAIL';
export const PROCESS_UNI_INFO_REQUEST = 'PROCESS_UNI_INFO_REQUEST';
export const PROCESS_UNI_INFO_SUCCESS = 'PROCESS_UNI_INFO_SUCCESS';
export const PROCESS_UNI_INFO_FAIL = 'PROCESS_UNI_INFO_FAIL';
export const PROCESS_DIL_INFO_REQUEST = 'PROCESS_DIL_INFO_REQUEST';
export const PROCESS_DIL_INFO_SUCCESS = 'PROCESS_DIL_INFO_SUCCESS';
export const PROCESS_DIL_INFO_FAIL = 'PROCESS_DIL_INFO_FAIL';
export const EDIT_PROCESS_OBS_REQUEST = 'EDIT_PROCESS_OBS_REQUEST';
export const EDIT_PROCESS_OBS_SUCCESS = 'EDIT_PROCESS_OBS_SUCCESS';
export const EDIT_PROCESS_OBS_FAIL = 'EDIT_PROCESS_OBS_FAIL';
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';